//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdidEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdidEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green 的本地化字符串。
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chromaticity Coordinates 的本地化字符串。
        /// </summary>
        public static string Color_PrimaryTitle {
            get {
                return ResourceManager.GetString("Color_PrimaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        public static string Color_White {
            get {
                return ResourceManager.GetString("Color_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string DataType_Advanced {
            get {
                return ResourceManager.GetString("DataType_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple 的本地化字符串。
        /// </summary>
        public static string DataType_Simple {
            get {
                return ResourceManager.GetString("DataType_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Transfer Characteristic 的本地化字符串。
        /// </summary>
        public static string Display_DisplayTransferCharacteristic {
            get {
                return ResourceManager.GetString("Display_DisplayTransferCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature Support 的本地化字符串。
        /// </summary>
        public static string Display_FeatureSupport {
            get {
                return ResourceManager.GetString("Display_FeatureSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Size 的本地化字符串。
        /// </summary>
        public static string Display_ScreenSize {
            get {
                return ResourceManager.GetString("Display_ScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Input 的本地化字符串。
        /// </summary>
        public static string Display_VideoInput {
            get {
                return ResourceManager.GetString("Display_VideoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Established Timing I 的本地化字符串。
        /// </summary>
        public static string EstablishedTimings_1 {
            get {
                return ResourceManager.GetString("EstablishedTimings_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Established Timing II 的本地化字符串。
        /// </summary>
        public static string EstablishedTimings_2 {
            get {
                return ResourceManager.GetString("EstablishedTimings_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer&apos;s Timings 的本地化字符串。
        /// </summary>
        public static string EstablishedTimings_Manufacturer {
            get {
                return ResourceManager.GetString("EstablishedTimings_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decoded Data 的本地化字符串。
        /// </summary>
        public static string Header_DecodedData {
            get {
                return ResourceManager.GetString("Header_DecodedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw data 的本地化字符串。
        /// </summary>
        public static string Header_RawData {
            get {
                return ResourceManager.GetString("Header_RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EDID Editor 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary 的本地化字符串。
        /// </summary>
        public static string Menu_EdidData_bin {
            get {
                return ResourceManager.GetString("Menu_EdidData_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Menu_EdidData_text {
            get {
                return ResourceManager.GetString("Menu_EdidData_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Menu_EdidExport {
            get {
                return ResourceManager.GetString("Menu_EdidExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Menu_EdidImport {
            get {
                return ResourceManager.GetString("Menu_EdidImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File(_F) 的本地化字符串。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer Name 的本地化字符串。
        /// </summary>
        public static string ProductInfo_Label_ManufacturerName {
            get {
                return ResourceManager.GetString("ProductInfo_Label_ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer Week 的本地化字符串。
        /// </summary>
        public static string ProductInfo_Label_ManufacturerWeek {
            get {
                return ResourceManager.GetString("ProductInfo_Label_ManufacturerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacture or Model Year 的本地化字符串。
        /// </summary>
        public static string ProductInfo_Label_ManufacturerYear {
            get {
                return ResourceManager.GetString("ProductInfo_Label_ManufacturerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Code 的本地化字符串。
        /// </summary>
        public static string ProductInfo_Label_ProductCode {
            get {
                return ResourceManager.GetString("ProductInfo_Label_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 的本地化字符串。
        /// </summary>
        public static string ProductInfo_Label_SerialNumber {
            get {
                return ResourceManager.GetString("ProductInfo_Label_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor &amp; Product 的本地化字符串。
        /// </summary>
        public static string ProductInfo_PrimaryTitle {
            get {
                return ResourceManager.GetString("ProductInfo_PrimaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor &amp; Product ID 的本地化字符串。
        /// </summary>
        public static string ProductInfo_TitleTips {
            get {
                return ResourceManager.GetString("ProductInfo_TitleTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Section_Color {
            get {
                return ResourceManager.GetString("Section_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptor 的本地化字符串。
        /// </summary>
        public static string Section_Descriptor {
            get {
                return ResourceManager.GetString("Section_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Display 的本地化字符串。
        /// </summary>
        public static string Section_Display {
            get {
                return ResourceManager.GetString("Section_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Established Timings 的本地化字符串。
        /// </summary>
        public static string Section_EstablishedTimings {
            get {
                return ResourceManager.GetString("Section_EstablishedTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Info 的本地化字符串。
        /// </summary>
        public static string Section_GeneralInfo {
            get {
                return ResourceManager.GetString("Section_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Timings 的本地化字符串。
        /// </summary>
        public static string Setion_StandardTimings {
            get {
                return ResourceManager.GetString("Setion_StandardTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversion 的本地化字符串。
        /// </summary>
        public static string Version_Label_Revision {
            get {
                return ResourceManager.GetString("Version_Label_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version_Label_Version {
            get {
                return ResourceManager.GetString("Version_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version &amp; Revision 的本地化字符串。
        /// </summary>
        public static string Version_PrimaryTitle {
            get {
                return ResourceManager.GetString("Version_PrimaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The EDID structure version number and revision number 的本地化字符串。
        /// </summary>
        public static string Version_TitleTips {
            get {
                return ResourceManager.GetString("Version_TitleTips", resourceCulture);
            }
        }
    }
}
